"""Build mikrotik_ui.py (the self-contained panel HTML) from ui/panel.html.

The official MCP Apps client (@modelcontextprotocol/ext-apps, Apache-2.0) is
embedded so the panel works offline. Run after editing ui/panel.html:

    python scripts/build_ui.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
bundle = (ROOT / "ui/vendor/ext-apps-app-with-deps.js").read_text(encoding="utf-8")

# Replace the ESM export statement with a global so a second inline module can use it.
m = list(re.finditer(r"export\{([^}]*)\};?", bundle))[-1]
names = {}
for part in m.group(1).split(","):
    local, _, exported = part.strip().partition(" as ")
    names[exported or local] = local
wanted = ["App", "applyDocumentTheme", "applyHostStyleVariables", "applyHostFonts"]
glob = "window.__extapps={" + ",".join(f"{k}:{names[k]}" for k in wanted) + "};"
bundle = bundle[:m.start()] + glob + bundle[m.end():]
bundle = bundle.replace("</script", "<\\/script")

html = (ROOT / "ui/panel.html").read_text(encoding="utf-8")
html = html.replace("/*__EXT_APPS_BUNDLE__*/", "/* @modelcontextprotocol/ext-apps (Apache-2.0) */\n" + bundle)

out = ROOT / "mikrotik_ui.py"
out.write_text('"""GENERATED by scripts/build_ui.py from ui/panel.html. Do not edit."""\n'
               f"PANEL_HTML = {html!r}\n", encoding="utf-8")
print(f"wrote {out} ({len(html) // 1024} KB)")
